   0	Abbasi, Sarmad
   1	Abderrezzak, Abdelhamid
   2	Abrate, Marco
   3	Abuku, Tomoaki
   4	Adam, David
   5	Adamczewski, Kamil
   6	Adegoke, Kunle
   7	Adelberg, Arnold
   8	Adell, Jos&eacute; A.
   9	Adeniran, Ayomikun
  10	Adiga, Chandrashekar
  11	Adolphson, Alan
  12	Aebi, Christian
  13	Agoh, Takashi
  14	Agust&iacute;n-Aquino, Octavio A.
  15	Ahmed, Tanbir
  16	Ahmia, Moussa
  17	Ait-Amrane, Lyes
  18	Aiylam, Dhroova
  19	Akbary, Amir
  20	Akhtar, Reza
  21	Akopyan, Arseniy
  22	Akula, Aditya
  23	Ak&uuml;z&uuml;m, Ye&scedil;im
  24	Alaca, Ay&scedil;e
  25	Alaca, &#350;aban
  26	Alanazi, Abdulaziz M.
  27	Alanazi, Jamilah
  28	Albert, Michael H.
  29	Alekseyev, Max A.
  30	Alexeev, Boris
  31	Alhakim, Abbas
  32	Ali, Debbache
  33	Alkan, Emre
  34	Allen, Edward E.
  35	Allen, M. R.
  36	Allouche, J.-P.
  37	Alm, Jeremy F.
  38	Alon, Noga
  39	Alpert, Hannah
  40	Altman, Harry
  41	Alvarado, Sa&uacute;l D&iacute;az
  42	Alvarez-Salazar, Elise
  43	Alves, Francisco Regis Vieira
  44	Alweiss, Ryan
  45	Alzer, Horst
  46	Amato, Roberto
  47	Ambrose, Christopher
  48	Amdeberhan, Tewodros
  49	Amirkhanyan, Gagik
  50	Ammons, Savana
  51	Amos, Jeff
  52	Andersen, A.S.
  53	Anderson, Ian
  54	Andrade, Julio C.
  55	Andrews, George E.
  56	Andrica, Dorin
  57	Angelo, Rodrigo
  58	Anglani, Roberto
  59	Anible, Emily E.
  60	Ansaldi, Katie
  61	Antony, Deepa
  62	Aoki, Miho
  63	Apagodu, Moa
  64	Apel, Geoffrey
  65	Arab, Meysam
  66	Araci, Serkan
  67	Ardal, Hayri
  68	Ardila, Rene
  69	Armbruster, Ashley
  70	&Aacute;rend&aacute;s, P&eacute;ter
  71	Ar&#305;kan, Talha
  72	Arnoux, Pierre
  73	Arroyo, Aubin
  74	Asca&ntilde;o, Joy P.
  75	Asinowski, Andrei
  76	Askgaard, Jens
  77	Asplund, John
  78	Assaf, Sami
  79	Athreya, Jayadev S.
  80	Athreya, Krishna B.
  81	Au, Yu-Hin
  82	Augspurger, C.
  83	Axenovich, Maria
  84	Axler, Christian
  85	Ayad, Mohamed
  86	Aygin, Zafer Selcuk
  87	Ayyad, Anwar
  88	Bachoc, C.
  89	Backman, Spencer
  90	Baczkowski, Daniel
  91	Bade, Tej
  92	Baglini, Lorenzo Luperi
  93	Bai, James Haoyu
  94	Baier, Stephan
  95	Bajnok, B&eacute;la
  96	Baker, Simon
  97	Bal, Hartosh Singh
  98	Balaji, Vajresh
  99	Balaji, Vishal
 100	Balasubramanian, R.
 101	Bal&aacute;&#382;i, Peter
 102	Bal&aacute;&#382;, Vladim&iacute;r
 103	Baldoni, Velleda
 104	Balkov&aacute;, L'ubom&iacute;ra
 105	Ballantine, Cristina
 106	Ballot, Christian
 107	Balog, Antal
 108	Bamunoba, Alex Samuel
 109	Bandyopadhyay, Subhajit
 110	Banerjee, Pradipto
 111	Banks, William D.
 112	Barai, Rakesh
 113	Barat, Guy
 114	Barber, Ben
 115	Barbero, Stefano
 116	Bardaji, Itziar
 117	Barequet, Gill
 118	Barger, Grace
 119	Baril, Jean-Luc
 120	Barile, Margherita
 121	Barman, Rupam
 122	Barrios, Alexander J.
 123	Bartz, Jeremiah
 124	Baruah, Nayandeep Deka
 125	Baruchel, Thomas
 126	Baskoro, E. T.
 127	Bates, Bruce
 128	Bat&#305;r, N.
 129	Batra, Sanjit Singh
 130	Bayless, Jonathan
 131	B&eacute;nyi, Be&aacute;ta
 132	Beal, Timothy Kevin
 133	Beck, George
 134	Beck, Matthias
 135	Beckwith, Olivia
 136	Beeler, Robert A.
 137	Behloul, Djilali
 138	Behum, Sharon E.
 139	Beideman, Calvin
 140	Belbachir, Hac&egrave;ne
 141	Belkhir, Amine
 142	Bell, George I.
 143	Bencherif, Farid
 144	Bencs, Ferenc
 145	Benesh, Bret
 146	Benjamin, Arthur T.
 147	Bennett, Michael A.
 148	Benyahia Tani, Nesrine
 149	B&eacute;nyi, Be&aacute;ta
 150	Berkove, Ethan
 151	Berline, Nicole
 152	Bersani, Alberto Maria
 153	Berth&eacute;, Val&eacute;rie
 154	Bertrand-Mathis, Anne
 155	Best, Andrew
 156	Beste, Meeri-Liisa
 157	Bevilacqua, Erin
 158	Bhanja, Jagannath
 159	Bhatnagar, Gaurav
 160	Shattacharjee, Sreerupa
 161	Bhoi, Kisan
 162	Bhowmick, Krishnendu
 163	Bhowmik, Gautami
 164	Bhuniya, A. K.
 165	Bhutani, Kiran R.
 166	Bialostocki, Arie
 167	Bibby, Sean
 168	Bidar, Mohammadreza
 169	Bierbrauer, Jurgen
 170	Binner, Damanvir Singh
 171	Birmajer, Daniel
 172	Blagouchine, Iaroslav V.
 173	Blair, D. Dakota
 174	Blair, Matthew
 175	Blanc, Lois
 176	Blanchet-Sadri, F.
 177	Blanco, Sa&uacute;l A.
 178	Blanchard, Peter F.
 179	Bl&aacute;zsik, Zolt&aacute;n L.
 180	Blecksmith, Richard
 181	Blodgett, Aaron
 182	Blokhuis, Aart
 183	Blomberg, Lars
 184	Blondel, Vincent D.
 185	Boca, Florin P.
 186	Bodor, Bertalan
 187	Bohra, Ayush
 188	Bonato, Anthony
 189	Bonde, Vedant
 190	Booker, Andrew R.
 191	Boothby, Tomas
 192	Bora, Jonali
 193	Borah, Padma Bhushan
 194	Borb&eacute;ly, J&oacute;zsef
 195	Bordell&egrave;s, Olivier
 196	Borges, A.
 197	Boros, Endre
 198	Boruah, Bidyaut
 199	Borwein, David
 200	Borwein, Jonathan M.
 201	Bosma, Wieb
 202	Bouroubi, Sadek
 203	Bousbaa, Imad-Eddine
 204	Boussayoud, Ali
 205	Bowen, Matthew
 206	Bower, Amanda
 207	Boyadzhiev, Khristo N.
 208	Boyer, Robert P.
 209	Bradford, Kyle
 210	Bramham, Alexander
 211	Braun, Benjamin
 212	Bray, Patrick F.
 213	Brenner, Hazel N.
 214	Brent, Barry
 215	Brent, Richard
 216	Bresz, Kellie
 217	Breuer, Felix
 218	Breuer, Florian
 219	Brewbaker, Chad
 220	Bridges, Walter
 221	Brillhart, John
 222	Brindle, Benjamin
 223	Broersma, H. J.
 224	Broughan, Kevin A.
 225	Brouwer, Andries E.
 226	Brown, Jim
 227	Brown, Kenneth A.
 228	Brown, Morgan V.
 229	Brown, Ron
 230	Brown, Tom C.
 231	Brunat, Josep M.
 232	Bruno, Jorge
 233	Brunotte, Horst
 234	Bu, AJ
 235	Budden, Mark
 236	Bugeaud, Yann
 237	Buhler, Joe
 238	Bunder, Martin W.
 239	Buontempo, Jenny
 240	Burke, Kyle
 241	Burt, David
 242	Burungale, Ashay
 243	Butler, Steve
 244	Bush, Albert
 245	Buzzard, Kevin
 246	Byard, Kevin
 247	Bykova, Sofya
 248	Byramji, Farzan
 249	Bystrzycki, Rafa&lstrok;
 250	Byrnes, Steven
 251	Bzd&#x0229;ga, Bart&#322;omiej
 252	Cai, Tianxin
 253	Cairns, Brant
 254	Cairns, Grant
 255	Caldwell, Chris K.
 256	Calkin, Neil J.
 257	Calkins, Nicole
 258	Callan, David
 259	Campbell, Andre&eacute; Alexander
 260	Campbell, Garikai
 261	Campbell, John Maxwell
 262	Campos, Helena
 263	Candela, Pablo
 264	Canfield, E. Rodney
 265	Cao, Xue-Qin
 266	Cao, Zhu
 267	Caple, Christine
 268	Carlos, Elise
 269	Carlson, Timothy J.
 270	Caro, Yair
 271	Carpi, Arturo
 272	Carter, Jamylle
 273	Carvalho, Alda
 274	Cass, Robert
 275	Cassell, Catherine
 276	Catarino, Paula Maria Machado Cruz
 277	Catt, Elliot
 278	Caveney, Geoffrey
 279	C&eacute;gielski, Patrick
 280	Celerier, Charles
 281	&#268;erin, Zvonko
 282	Cerruti, Umberto
 283	Chabert, Jean-Luc
 284	Chaichana, Tuangrat
 285	Chakraborty, Aninda
 286	Chan,  Heng Huat
 287	Chan, Song Heng
 288	Chan, Tsz Ho
 289	Chan, W. H.
 290	Chandler, Ray
 291	Chaney, Zachary
 292	Chang, Mei-Chu
 293	Chaopraknoi, Sureeporn
 294	Chaplick, Steven
 295	Chapman, Jeremy
 296	Chapman, Robin
 297	Chapman, Scott T.
 298	Chappelon, Jonathan
 299	Charlier, Emilie
 300	Chase, Zachary
 301	Chattopadhyay, Jaitra
 302	Chaudhary, M. P.
 303	Chebolu, Sunil K.
 304	Checa, Daniel F.
 305	Chen, Bin
 306	Chen, Fang
 307	Chen, Feng-Juan
 308	Chen, Kuo-Jye
 309	Chen, Li-Chung
 310	Chen, Shi-Chao
 311	Chen, Yong-Gao
 312	Chen, Young-Ming
 313	Chen, Yung-Pin
 314	Chen, Xi
 315	Cheng, Yin Choi
 316	Chern, Shane
 317	Cherukupally, Srikanth
 318	Cheslack-Postava, Tegan
 319	Chikin, Nikolay
 320	Chim, Kwok Chi
 321	Chintamani, Mohan N.
 322	Chinwarakorn, Sirawich
 323	Chipeniuk, Karsten
 324	Chitmung, Natthaphong
 325	Choi, Jongwoo
 326	Choi, Yunseo
 327	Choliy, Yuriy
 328	Choudhry, Ajai
 329	Christober, M. Davamani
 330	Christopher, A. David
 331	Chu, H&#249;ng Vi&#7879;t
 332	Chu, Wenchang
 333	Chung, Chan-Liang
 334	Chung, Fan
 335	Chung, Matthew
 336	Chung, Ping Ngai
 337	Ciere, Michael
 338	Cilleruelo, Javier
 339	Cincotti, Alessandro
 340	Cipra, James Arthur
 341	Cipu, Mihai
 342	Clark, Lane
 343	Clark, Pete L.
 344	Clark, Steven P.
 345	Clayton, Graeme
 346	Clem, Stian
 347	Clifton, Justin
 348	Clow, A.
 349	Cobeli, Christian
 350	Cobo, Helena
 351	Cochrane, Albert
 352	Cochrane, Todd
 353	Coelho, Franscisco
 354	Cohen, Graeme L.
 355	Cohen, Joel E.
 356	Coleman, Deidra
 357	Collins, David
 358	Connolly, Samuel
 359	Coons, Michael
 360	Cooper, Benjamin
 361	Cooper, Curtis
 362	Cooper, Joshua
 363	Cooper, Shaun
 364	Coppersmith, Don
 365	Coppo, Marc-Antoine
 366	Coppola, G.
 367	Cordwell, Katherine
 368	Corr&aacute;di, Kereszt&eacute;ly
 369	Correll, Jr., Bill
 370	Corteel, Sylvie
 371	Cosgrave, John B.
 372	Courtright, Kevin M.
 373	Cox, Danielle
 374	Crabill, Doug
 375	Crandall, Richard
 376	Cri&#537;an, Drago&#537;
 377	Croot, Ernie
 378	Cruz, Helena Mart&iacute;n
 379	Csernenszky, Andr&aacute;s
 380	Cui, Kelly
 381	Cullinan, John
 382	Culver, Clay
 383	Curran, Stephen J.
 384	Currie, James D.
 385	Curtis, Dawn
 386	Cusick, Thomas W.
 387	Dai, Haobo
 388	Dai, Li-Sia
 389	Dailly, Antoine
 390	Dajani, Karma
 391	D'Alonzo, Valerio
 392	Damir, Mohamed Taoufiq
 393	Dang, Sakshi
 394	Darling, R. W. R.
 395	Das, Shamik
 396	Das Adhikari, Sukumar
 397	Dasher, A. Suki
 398	de Castro, Dario T.
 399	da Silva, Robson
 400	Dastidar, Manosij G.
 401	Daugherty, Zajj
 402	Davenport, Dennis E.
 403	David, Chantal
 404	Davis, Donald M.
 405	Davis, Julia
 406	Davis, Robert
 407	Ddamulira, Mahadi
 408	De, Dibyendu
 409	Deaconescu, Marian
 410	Dean, Nathaniel
 411	Dearden, Bruce
 412	Debnath, Pintu
 413	Defant, Colin
 414	de Jesus, M. N.
 415	de Jonge, Jaap
 416	Dekking, Michel
 417	de Koninck, Jean-Marie
 418	De Loera, Jes&uacute;s A.
 419	Demaine, Erik D.
 420	Depret-Guillaume, James S.
 421	de Reyna, J. Arias
 422	DeSalvo, Stephen
 423	de Sousa, Renata Te&oacute;filo
 424	De Wannamacker, Steve
 425	de Weger, Benne
 426	de Wiljes, Jan-Hendrik
 427	Delbourgo, Daniel
 428	Delcourt, Michelle
 429	Delorme, Charles
 430	Deng, Guixin
 431	Deng, Yingpu
 432	Derbal, Abdallah
 433	Deshouillers, Jean-Marc
 434	Deutsch, Emeric
 435	Deutsch, Jesse Ira
 436	Deveci, &Ouml;m&uuml;r
 437	Devlin, Patrick
 438	DeVos, Matt
 439	Dey, Pallab Kanti
 440	Di Biagio, Lorenzo
 441	Di Claudio, Leontina Veliana
 442	Di Nasso, Mauro
 443	Dias, C&aacute;tia Lente
 444	Dick, Josef
 445	Diesl, Alexander
 446	Diffenderfer, James D.
 447	Dil, Ayhan
 448	Dilcher, Karl
 449	Diomidov, Yevhenii
 450	Disanto, Filippo
 451	Dobson, John Blythe
 452	Doering, Jessica
 453	Doerksen, Kevin
 454	Dorbec, Paul
 455	dos Santos, Carlos Pereira
 456	Dougherty-Bliss, Robert
 457	Douglas, Ian
 458	Dove, Andrew P.
 459	Doyon, Nicolas
 460	Doyle, Greg
 461	Doyon, Nicolas
 462	Drake, Nate
 463	Drema, Rinchin
 464	Dresden, Greg
 465	Drummond-Cole, Gabriel C.
 466	Du, Daniel D.
 467	Duan, Heli
 468	Duan, Shu-Juan
 469	Dubickas, Art&#363;ras
 470	Duch&ecirc;ne, Eric
 471	Dudek, Andrzej
 472	Dufour, Matthieu
 473	Dujella, Andrej
 474	Dukes, Peter J.
 475	Duncan, Breille
 476	Dunn, Scott M.
 477	Dupuy, Benjamin
 478	Duran, &Ouml;mer
 479	Durham, Gabriel
 480	Dutour, Mathieu
 481	Dutra, Brandon E.
 482	Dutta, Mridul
 483	Dutta, Utkal Keshari
 484	Dvoracheck, Tyler
 485	Dvo&rcaron;&aacute;kov&aacute; (born Balkov&aacute;), L'ubom&iacute;ra
 486	Dwivedi, Himanshu Kumar
 487	Dwivedi, Srashti
 488	Dwyer, Aaron
 489	Dynes, Patrick
 490	Dziemia&#x00144;czuk, M.
 491	Earnest, A. G.
 492	Eaton, Rachel
 493	Eckard, Emily
 494	Edel, Yves
 495	Edelsbrunner, Xixi
 496	Edgar, Tom
 497	Edjeou, Bilizimb&eacute;y&eacute;
 498	Edson, Marcia
 499	Edwards, Olivai
 500	Egbert, Nick
 501	Eger, Steffen
 502	Egge, Eric S.
 503	Eichhorn, Dennis
 504	Eickemeyer, Andrew
 505	Eigen, S.
 506	Einstein, David
 507	Eitner, Justin
 508	Ekhad, Shalosh B.
 509	El Bachraoui, Mohamed
 510	El Turkey, Houssein
 511	Eldredge, Michael G.
 512	ElDin, Ramy F. Taki
 513	Elia, Marcus
 514	Eliahou, Shalom
 515	Elias, Yara
 516	Elizeche, Edgar Federico
 517	Elkhiri, Laid
 518	Ella, Sophia
 519	Elledge, Shawn
 520	Elliott, Jesse
 521	Elsner, Carsten
 522	Emadian, Elliot R.
 523	Emanuel, Paul Robert
 524	Emme, Jordan
 525	Emory, Melissa
 526	Endrullis, J&ouml;rg
 527	Engberg, Zebediah
 528	Engbers, John
 529	Epstein, Alyssa
 530	Erban, Radek
 531	Erdahl, Robert
 532	Erde, Joshua
 533	Erd&#337;s, Paul
 534	Ericksen, Larry
 535	Eriksson, Kimmo
 536	Ernst, Dana C.
 537	Esmaeili, Morteza
 538	Eustis, Alex
 539	Evans, Anthony B.
 540	Evans, C. D. A.
 541	Evans, Ron
 542	Evans, Tyler J.
 543	Everett, William B.
 544	Fan, Kai (Steve)
 545	Fan, Yushuang
 546	Fang, Jin-Hui
 547	Fares, Youssef
 548	Farhadian, Reza
 549	Farhangi, Sohail
 550	Farhi, Bakir
 551	Farrokhi D. G., Mohammad
 552	Faure, Henri
 553	Faye, Bernadette
 554	Fel, Leonid G.
 555	Fellman, Tasha
 556	Fellman, Todd
 557	Feng, Cong-Jiao
 558	Feng, Li
 559	Ferland, Matthew
 560	Fernando, Neranga
 561	Ferrari, Luca
 562	Ferrari, Matteo
 563	Fickes, Grant
 564	Fidkowski, Lukasz M.
 565	Filaseta, Michael
 566	Filipovski, Slobodan
 567	Finbow, S.
 568	Finch(-Smith), Carrie
 569	Finch, Steven R.
 570	Finch-Smith, Carrie
 571	Fink, Alex
 572	Firicel, Alina
 573	Fish, Sara
 574	Fisher, Michael
 575	Fitzgerald, Robert W.
 576	Fletcher, Peter
 577	Fl&oacute;rez, Jorge
 578	Fl&oacute;rez, Rigoberto
 579	Fl&oacute;rez, Rigoberto
 580	Flori, Jean-Pierre
 581	Florian, Josef
 582	Flowers, Timothy B.
 583	Foo, Timothy
 584	Ford, Kevin
 585	Fox, Jacob
 586	Fox, N. Bradley
 587	Fox, Nathan
 588	Fraenkel, Aviezri S.
 589	France, M. Mend&egrave;s
 590	Francis, Forrest J.
 591	Franke, Johann
 592	Franzone, Katherine
 593	Fraser, William
 594	Freedman, Allen R.
 595	Freeman, John M.
 596	Fried, Katalin
 597	Friedman, Eric J.
 598	Freiling, Chris
 599	Freiman, Gregory A.
 600	Freitas, G&eacute;rsica
 601	Friedlander, John B.
 602	Frigeri, Achille
 603	Frontczak, Robert
 604	Frougny, Christiane
 605	Fu, Shishuo
 606	Fuchs, Clemens
 607	Fujisawa, Yusuke
 608	Fukui, Masanori
 609	Gaebler, Robert
 610	Gabor, Zachary
 611	Gaede, Tao
 612	Gaiser, Collier
 613	Gaitanas, Konstantinos
 614	Gallardo, Luis H.
 615	Ganzell, Sandy
 616	Gao, Alice L.L.
 617	Gao, Peng
 618	Gao, Shanzhen
 619	Gao, Weidong
 620	Gao, Zhenguang
 621	Gao, Zhicheng
 622	Garc&iacute;a, Victor Cuauhtemoc
 623	Garc&#237;a-Pulgar&#237;n, Gilberto
 624	Garc&iacute;a-S&aacute;nchez, Pedro A.
 625	Garge, Anuradha S.
 626	Garrabrant, Scott M.
 627	Garrity, Thomas
 628	Gassert, T. Alden
 629	Gates, Zachary
 630	Gavel, Hillevi
 631	Geneson, Jesse
 632	Georgakopoulos, Agelos
 633	Georges, John P.
 634	Gerhold, Stefan
 635	Germain, Jam
 636	Geroldinger, Alfred
 637	Gessel, Ira M.
 638	Ghosh, Swapan Kumar
 639	Gianella, Gian Mario
 640	Gibbs, Philip
 641	Gibson, D. Jason
 642	Gibson, Maghann Moriah
 643	Gil, Juan B.
 644	Gilmer, J.
 645	Gimbel, Steven
 646	Ginosar, Yuval
 647	Gireesh, D. S.
 648	Giraldo, Hern&aacute;n
 649	Girard, Benjamin
 650	Girgensohn, Roland
 651	Girstmair, Kurt
 652	Glass, Darren B
 653	Glebsky, Lev
 654	Gledel, Valentin
 655	Glenn, Jeske
 656	Glunz, Henry
 657	G&oacute;mez-Flores, Axel O.
 658	Goadrich, Mark
 659	Godbole, Anant
 660	Goddard, Bart
 661	Goddyn, Luis
 662	Godinho, Hemar
 663	Goff, Michael
 664	Goh, Marcel K.
 665	Goins, Edray Herber
 666	Goldbring, Isaac
 667	Goldstein, Eli
 668	Goldwasser, John
 669	Gonz&aacute;lez, Marcos J.
 670	Gonz&aacute;lez, Oscar E.
 671	Good, Jack
 672	Gordon, Russell A.
 673	Goswami, Sayan
 674	Gotou, Rin
 675	Goubi, Mouloud
 676	Gould, H. W.
 677	G&ouml;ral, Haydar
 678	Goy, Taras
 679	Graham, Ron
 680	Grantham, Jon
 681	Gravel, Claude
 682	Graves, Hester
 683	Gray, Daniel
 684	Griggs, Jerrold R.
 685	Grinberg, Darij
 686	Groen, Steven R.
 687	Grubb, Thomas
 688	Grundman, Helen G.
 689	Grynkiewicz, David J.
 690	Grytczuk, Jaros&lstrok;aw
 691	Gueco, Edna N.
 692	Gugg, Chadwick
 693	Guhl, Matthew
 694	Guiben, Salem
 695	Gullerud, Emily
 696	Guo, Bai-Ni
 697	Guo, Victor Z.
 698	Guo, Yu-Hong
 699	Gurvich, Vladimir
 700	Gutekunst, Samuel
 701	Guttierez, Marcela
 702	Guy, R. K.
 703	Gy, Ren&eacute;
 704	Gyarmati, Katalin
 705	Hadjicostas, Petros
 706	Haff, L. R.
 707	Hall-Seelig, Laura L.
 708	Hamkins, Joel David
 709	Hamm, Jessica
 710	Hammer, James
 711	Han, Sandie
 712	Handley, B.
 713	Hansen, Cody
 714	Hansen, Cody S.
 715	Harborth, Heiko
 716	Harrington, Joshua
 717	Harris, Pamela E.
 718	Hasanalizade, Elchin
 719	Hassani, Mehdi
 720	Hatley, Jeffrey
 721	Haukkanen, Pentti
 722	Havens, Christopher Robin
 723	Hayward, Ryan B.
 724	Hedetniemi, Jason
 725	Hedge, Shruti
 726	Hegarty, Peter
 727	Heged&#369;s, G&aacute;bor
 728	Hegyv&aacute;ri, Norbert
 729	Heinrich, Marc
 730	Hemmandy, Anand
 731	Henaku, Calvin
 732	Henderson, Philip
 733	Hendrickx, Julien M.
 734	Hendriks, Dimitri
 735	Hennecart, Fran&ccedil;ois
 736	Herden, Daniel
 737	Hermida, A.
 738	Hern&aacute;ndez, Santos Hern&aacute;ndez
 739	Hertlein, Alexander
 740	Herzinger, Kurt
 741	Heubach, Silvia
 742	Heuberger, Clemens
 743	Heyman, Randell
 744	Hiary, Ghaith
 745	Hicks, Jacob
 746	Higashitani, Akihiro
 747	Higgins, Zach
 748	Higuita, Robinson A.
 749	Hildebrand, A.J.
 750	Hilgart, Tobias
 751	Hiller, Josh
 752	Hindman, Neil
 753	Hine, Natalie
 754	Hines, Taylor
 755	Hirschberg, Daniel S.
 756	Hirschhorn, Michael
 757	Hirshberg, susan
 758	Hisert, George A.
 759	Ho, Nhan Bao
 760	Ho, Pak Tung
 761	Ho, Randy W.
 762	Hoffman, Michael E.
 763	Hogan, M. S.
 764	Hoit, Abigail
 765	Holdum, Sebastian Tim
 766	Holliday, Sarah H.
 767	Holshouser, Arthur
 768	Holt, Benjamin V.
 769	Hopkins, Brian
 770	Hopkins, Kimberly
 771	Horan, Victoria
 772	Horn, Paul
 773	Horrocks, David G. C.
 774	Horrocks, Jonathan H.
 775	Horvath, Gabor
 776	Ho&scedil;ten, Serkan
 777	Hou, Qing-Hu
 778	Hsu, Leetsch C.
 779	Hu, Yining
 780	Hu, Yongzhong
 781	Hua, Guodong
 782	Hua, Ting
 783	Huggan, Melissa
 784	Huguet, Janitzio Mej&iacute;a
 785	Hui, Chun Yin
 786	Huicochea, Mario
 787	Humby, George
 788	Hungerbuhler, Norbert
 789	Huntemann, Svenja
 790	Hurlbert, Glenn H.
 791	Hussein, Saud
 792	Hyatt, Matthew
 793	Iba, Victoria
 794	Iiams, Joel
 795	Imatomi, Kohtaro
 796	Imbert, Laurent
 797	Inaba, Youichi
 798	Inoue, Maakito
 799	Insko, Erik
 800	Ionascu, Eugen J.
 801	Iordache, Adrian
 802	Iosevich, Alex
 803	Irie, Yuki
 804	Isaacson, Brad
 805	Ismailescu, Dan
 806	Isnaini, Uha
 807	Ito, Shunji
 808	Jacobs, R.
 809	Jakimczuk, Rafael
 810	James, Jeffery
 811	James, Kevin
 812	Jana, Subhajit
 813	Janardhanan, Mano Vikash
 814	Jani, Mahendra
 815	J&auml;rleberg, Erik
 816	Jaroma, John H.
 817	Jenkins, Hugo
 818	Jenkins, Paul
 819	Jenkins, Scott
 820	Jha, Sumit Kumar
 821	Jia, Chang-Kun
 822	Jiang, Wen
 823	Jin, Hai-Tao
 824	Jin, Renling
 825	Jiu, Lin
 826	Jobson, Adam
 827	Johnson, John H.
 828	Johnson, Katie
 829	Johnson, Keith
 830	Jones, Edna
 831	Jones, Lenny
 832	Jonsson, Markus
 833	Jordan, Jill E.
 834	Jouhet, Fr&eacute;d&eacute;ric
 835	Joyner, David
 836	Juarez, Jazmine
 837	Juillerat, Jacob
 838	Junes, Leandro
 839	Jungers, Rapha&euml;l M.
 840	Jungi&#263, Veselin
 841	Just, Matthew
 842	Juyal, Abhishek
 843	Kafle, Bir
 844	Kahane, J.-P.
 845	Kahkeshani, Reza
 846	Kahrobaei, Delaram
 847	Kainhofer, Reinhold
 848	Kalle, Charlene
 849	Kallus, Margaret G.
 850	Kalmynin, A. B.
 851	Kamano, Ken
 852	Kanasri, N. R.
 853	Kane, Daniel M.
 854	Kaneko, Hajime
 855	Kang, Jeong-Hyun
 856	Kang, Ross J.
 857	Kannan, S. S.
 858	Kanungo, Siddhartha
 859	Kao, Kuo-Yuan
 860	Kapbasov, Ardak
 861	Kapbasov, Arman
 862	Kaplan, Gil
 863	Kaplan, Nathan
 864	Kar, Nirupam
 865	Karaatli, Olcay
 866	Karabulut, Cihan
 867	Karaivanov, Borislav
 868	Kariv, Jonathan
 869	K&aacute;rolyi, Gyula
 870	Kathiravan, T.
 871	Katriel, Jacob
 872	Katsipis, Nikos
 873	Kaur, Mandeep
 874	Kawasaki, Naho
 875	Kay, Bill
 876	Kaye, Ian
 877	Kazda, Alexandr
 878	Keane, Michael
 879	Keaton, Rodney
 880	Keilthy, Adam
 881	Keister, Derrick M.
 882	Keith, William J.
 883	Kellner, Bernd C.
 884	Kelvey, Robert
 885	Kemkes, Graeme
 886	Kendrick, Caleb
 887	Kendirli, Bar&inodot;&scedil;
 888	Kerada, Mohamed
 889	Kervaire, Michel
 890	Kesicio&#287;lu, Yavuz
 891	Khan, Bilal
 892	Khan, Mizan R.
 893	Khodkar, Abdollah
 894	Khomovsky, Dmitry I.
 895	Khongsit, S.
 896	Khoshnam, Foad
 897	Kifer, Curtis
 898	Kihel, Omar
 899	K&#305;l&#305;&ccedil;, Emrah
 900	Kim, Byeong Moon
 901	Kim, Byungchan
 902	Kim, Dae San
 903	Kim, Insuk
 904	Kim, John Y.
 905	Kim, Seoyoung
 906	Kim, Sungjin
 907	Kim, Young Jin
 908	Kimberling, Clark
 909	King, Adam J.
 910	King, Dylan
 911	King, Samuel
 912	Kinlaw, Paul
 913	Kirgizov, Sergey
 914	Kirillov, Juri
 915	Kirschenhofer, Peter
 916	Kirschmer, Markus
 917	Kiss, S&aacute;ndor Z.
 918	Kitaev, Sergey
 919	Kitaoka, Yoshiyuki
 920	Kitrossky, Levi
 921	Klausen, Frederik Ravn
 922	Klazar, Martin
 923	Klop, Jan Willem
 924	Klouda, Karel
 925	Klyve, Dominic
 926	Knapp, Michael P.
 927	Knop, Konstantin
 928	Knopfmacher, A.
 929	Koch, Zoe
 930	Koh, Doowon
 931	Kohl, Karen T.
 932	K&ouml;kl&uuml;ce, B&uuml;lent
 933	Kolitsch, Louis W.
 934	Komatsu, Takao
 935	Kominers, Scott Duke
 936	Komornik, Vilmos
 937	Konstantogiannis, Spiros
 938	Kontorovich, Alex
 939	Konyagin, Sergei V.
 940	Kook, Woong
 941	Koparal, Sibel
 942	K&oacute;rus, P&eacute;ter
 943	K&ouml;ppe, Matthias
 944	Kops, J. Christopher
 945	Koshy, Thomas
 946	Kosovali&cacute;, Nemanja
 947	Kouril, Michal
 948	Kowalenko, Victor
 949	K&rcaron;&iacute;&zcaron;ek, Michal
 950	Kraaikamp, Cor
 951	Krattenthaler, Christian
 952	Krause, Adam
 953	Kravitz, Noah
 954	Krawchuk, Colin
 955	Kritschgau, J&uuml;rgen
 956	Kreh, Martin
 957	Kritzer, Peter
 958	K&#345;&iacute;&#382;ek, Michal
 959	Kronholm, Brandt
 960	Kruczek, Klay
 961	Kr&uuml;ger, Oliver
 962	Krylov, Nikolai A.
 963	Kuba, Markus
 964	Kubelka, Richard P.
 965	Kuhapatanakul, Kantaphon
 966	Kukla, Andrzej
 967	Kumar, Abhimanyu
 968	Kumar, Balesh
 969	Kumar, Hitesh
 970	Kumar, Manish
 971	Kumar, Nikhil
 972	Kumar, Shiv Datt
 973	Kumchev, Angel V.
 974	Kurlberg, P&auml;r
 975	Kurt, Veli
 976	Kushwaha, Seema
 977	Kwong, Harris
 978	Kwong, Man Kam
 979	Kyll&ouml;nen, Urpo M.
 980	Labelle, Antoine
 981	Lagarias, Jeffrey C.
 982	Lages, Ant&oacute;nio
 983	Lal&iacute;n, Matilde
 984	Lam, Heung Yeung
 985	Lamarche, Alicia
 986	Lambert, Joshua
 987	Lampret, Vito
 988	Lan, Bin
 989	Landman, Bruce
 990	Landsberg, Adam Scott
 991	Lane-Harvard, Liz
 992	Langeveld, Niels
 993	Langlois, Bruno
 994	Lanning, Charles
 995	Lao, Huixue
 996	Laohakosol, Vichian
 997	Lapointe, M&eacute;lodie
 998	Larsen, Bayley
 999	Larson, C. E.
1000	Larson, Matt
1001	Larsson, Urban
1002	Lazarev, Oleg
1003	Law, Shirley
1004	Leach, David
1005	Lebowitz-Lockard, Noah
1006	Ledoan, Andrew H.
1007	Lee, Ethan S.
1008	Lee, Jaewoo
1009	Lee, Jun Ho
1010	Lee, Philip
1011	Lee, Si Ying
1012	Lee, Sunyoung
1013	Lefmann, Hanno
1014	Lehmann, Hunter
1015	Lekuona, Alberto
1016	Lelis, Jean
1017	Lengyel, Tam&aacute;s
1018	Lentfer, John
1019	Leonessi, Davide
1020	Lepinski, Mathew
1021	Leroy, Julien
1022	LeSaulnier, Tim
1023	Leth, Steven
1024	Lettington, Matthew C.
1025	Leung, Ho-Hon
1026	Leung, Wing Hong
1027	Lev, Vsevolod F.
1028	Levy, Dan
1029	Levy, Karl
1030	Lewis, Max
1031	Lewis, Ryan H.
1032	Lewis, Scott
1033	Lewittes, Joseph
1034	Li, Bei
1035	Li, Chun
1036	Li, Deyaun
1037	Li, Haifeng
1038	Li, Hsuan-Chu
1039	Li, Jinjiang
1040	Li, Rusen
1041	Li, Shiyu
1042	Li, Shuguang
1043	Li, Taiyu
1044	Li, Teresa X.S.
1045	Li, Ting Hon Stanford
1046	Li, Xian-Jin
1047	Li, Xiaoping
1048	Li, Yangcheng
1049	Li, Yuan
1050	Li, Yuanlin
1051	Li, Zhangyuan
1052	Li, Zhao-Jun
1053	Li, Zhonghua
1054	Liardet, Pierre
1055	Lichtblau, Daniel
1056	Lichtman, Jared Ducker
1057	Lidick&yacute;, Bernard
1058	Lim, Chang Mou
1059	Lim, Chu-Wee
1060	Lim, Dongkyu
1061	Lin, Hsueh-Yung
1062	Lin, Ying-Jie
1063	Linz, William
1064	Liqun, Tao
1065	Liskovets, Valery A.
1066	Litsyn, Simon
1067	Liu, Dan
1068	Liu, Guodong
1069	Liu, Ji-Cai
1070	Liu, Wen An
1071	Liu, Yang P.
1072	Liu, Zhi-Guo
1073	Ljuji&#263;, &#381;eljka
1074	L&oacute;pez, Josefina
1075	Lockard, Shannon
1076	Locke, Stephen C.
1077	Loehr, Nicholas A.
1078	Loftin, Anne Marie
1079	Lohr, Andrew
1080	Lombaers, Peter
1081	Lomel&iacute;, Ana Cecilia Garc&iacute;a
1082	Lopes, Jos&eacute; Othon
1083	Lopes, Pedro
1084	L&oacute;pez, Josefina
1085	Loomis, Paul
1086	Loreti, Paola
1087	Lott, Adam
1088	Lott, Andrew
1089	Louchard, Guy
1090	Lovejoy, Jeremy
1091	Loveless, Andrew D.
1092	Low, Richard M.
1093	Lu, Qing-Lin
1094	Luca, Florian
1095	Luckner, Thomas
1096	Lumley, Allysa
1097	Luntzlara, Noah
1098	Luo, Jiagui
1099	Luo, Victor
1100	Luo, Wenyu
1101	Luong, Tran Dihn
1102	Lupini, Martino
1103	Lyall, Neil
1104	Lyzinski, Vince
1105	Ma, Shilin
1106	Ma, Xin-Rong
1107	Ma, Yingbin
1108	Maamra, Mohammed Said
1109	Maaouia, Mohamed Ben Fraj Ben
1110	Ma&ccaron;aj, Martin
1111	Mac&iacute;as, Jhixon
1112	MacMillan, Kieren
1113	Mackenzie, Dana
1114	Magner, Richard
1115	Magness, Elsa
1116	Maharaj, Hiren
1117	Mahlburg, Karl
1118	Maitland, Christopher
1119	Maitra, Subhamoy
1120	Makino, Kazuhisa
1121	Maleki, Amir
1122	Manabe, Hikaru
1123	Mangerel, Alexander P.
1124	Mangueira, Milena Carolina dos Santos
1125	Manhart, Ethan
1126	Mani, Arun P.
1127	Manske, Jacob
1128	Manski, Sarah
1129	Mansour, Toufik
1130	Marcovecchio, Raffaele
1131	Marcovici, Ir&egrave;ne
1132	Maresch, Gabriel
1133	Mar&iacute;n, J.M.
1134	Markovich, Maria
1135	Markstr&ouml;m, Klas
1136	Marler, Jonathan J.
1137	Maroti, Attila
1138	Marques, Diego
1139	Martin, Greg
1140	Martin, Harold W.
1141	Martin, James B.
1142	Martin, Ryan R.
1143	Martinez, Conrado
1144	Mart&iacute;nez, Fabio Enrique Brochero
1145	Martinjak, Ivica
1146	Martinsson, Anders
1147	Mas&aacute;kov&aacute;, Zuzana
1148	Masubuchi, H.
1149	Masuda, Ariane M.
1150	Matolcsi, M.
1151	Matsuda, Kazuhide
1152	Matsuki, Norichika
1153	Mattarei, Sandro
1154	Mattes, Connor
1155	Matthews, Gretchen L.
1156	Matveev, Andrey O.
1157	Maureso, Montserrat
1158	Mauro, David W.
1159	Mayers, Nicholas W.
1160	Mayle, Jacob
1161	Mays, Michael E.
1162	Mazhouda, Kamel
1163	Mazumdar, Eshita
1164	Mazur, Marcin
1165	Mbarki, Khadija
1166	Mbirika, aBa
1167	McAllister, Tyrrell B.
1168	McAnally, Nathan
1169	McCarthy, Dermot
1170	McCarty, Viola
1171	McCurdy, Sarah K.
1172	McDonald, Alex
1173	McDonald, Brian
1174	McDonald, Daniel C.
1175	McGaughlin, James
1176	McGown, Kevin J.
1177	Mcharo, Solomon
1178	McIntosh, Richard J.
1179	McKay, Ghislain
1180	McKay, Neil A.
1181	McKenzie, Pierre
1182	Mc Laughlin, James
1183	McNew, Nathan
1184	Meadows, Alex
1185	Medina, Luis A.
1186	Meehan, Sean
1187	Meek, Tommy
1188	Meemark, Yotsanan
1189	Mehdizadeh, Marzieh
1190	Mei, Shu-Yuan
1191	Mekkaoui, Mohammed
1192	Meleshko, Joseph
1193	Melham, R. S.
1194	Melles, Caroline
1195	Menard, Jed
1196	Mennen, Carminda M.
1197	Mercer, Idris
1198	Merikoski, Jorma K.
1199	Merlini, Donatella
1200	Mertens, Michael H.
1201	Mesdal, G. A.
1202	Meyerowitz, Aaron
1203	Mez&#337;, Istv&aacute;n
1204	Mhanna, Antoine
1205	Miao, Rong
1206	Micek, Piotr
1207	Michael, T. S.
1208	Mihoubi, Miloud
1209	Miller, Joe
1210	Miller, Steven J.
1211	Milley, Rebecca
1212	Mills, Donald
1213	Minter, M.
1214	Mintos, Alexia S.
1215	Mishra, Bhawesh
1216	Mistri, Raj Kumar
1217	Mitchell, Patrick
1218	Miyadera, Ryohei
1219	Mizuhara, Matthew S.
1220	Moen, Courtney
1221	Moffie, Micha
1222	Moghaddamfar, A. R.
1223	Mohammadi, Ali
1224	Mohammed, Mohamud
1225	Mohsenipour, Shahram
1226	Moll, Victor H.
1227	Molla, Md Ibrahim
1228	Molnar-Saska, Ildiko
1229	Momihara, Koji
1230	Moncel, Julien
1231	Mondal, Santanu
1232	Monks, Keenan
1233	Mono, Andreas
1234	Monopoli, Francesco
1235	Montejano, Amanda
1236	Moody, Dustin
1237	Morales, Marina C.
1238	More, Yogesh
1239	Moree, Pieter
1240	Morgan, Hannah
1241	Morgenbesser, Johannes F.
1242	Mori, Katsuya
1243	Morier-Genoud, Sophie
1244	Moriya, B. K.
1245	Morrill, Thomas
1246	Morrison, Robert
1247	Moscariello, Alessio
1248	Moses, Peter J. C.
1249	Mosley, William Colin
1250	Moyer, Tatiana
1251	Mukherjee, Antara
1252	Mukherjee, Sajal Kumar
1253	Mullen, Todd
1254	Muller, Tom
1255	Munagi, Augustine O.
1256	Munarini, Emanuele
1257	Munday, Sara
1258	M&uuml;nkel, Florian
1259	Murru, Nadir
1260	Muskat, Joseph B.
1261	Mutafchiev, Ljuben
1262	M&uuml;yesser, Alp
1263	Myers, Kellen
1264	Nagy, G&aacute;bor V.
1265	Naika, M. S. Mahadeva
1266	Naimi, Ramin
1267	Nakamura, Shunsuke
1268	Nakano, Fumihiko
1269	Nakaya, Yushi
1270	Namboothiri, K Vishnu
1271	Nanoti, Saraswati
1272	Nansoko, Souleymane
1273	Narayan, Darren A.
1274	Narayanan, Shyam
1275	Nash, Lexi
1276	Naslund, Eric
1277	Natalini, Pierpaolo
1278	Nataraj, Karthik
1279	Nath, Rishi
1280	Nathanson, Melvyn B.
1281	Ndong, Florent Nguema
1282	Nedela, Roman
1283	Nedev, Zhivko
1284	N&eacute;meth, L&aacute;szl&oacute;
1285	Ne&#353;et&#345;il, Jaroslav
1286	Neto, Jo&atilde;o Pedro
1287	Neuhauser, Markus
1288	Nevans, C. Wesley
1289	Newman, David
1290	Nkonkobe, Sithembele
1291	Nguyen, Hieu D.
1292	Nguyen, Hoi H.
1293	Nicholson, John W.
1294	Nicolae, Florin
1295	Nicolas, Jean-Louis
1296	Niederhausen, Heinrich
1297	Nielsen, Pace P.
1298	Nienborg, Hauke
1299	Nitica, Viorel
1300	Niu, Chuan-Ze
1301	Noble, Matt
1302	Noll, Jenna
1303	Normenyo, Benedict Vasco
1304	Nowakowski, Richard J.
1305	Ntienjem, Eb&eacute;n&eacute;zer
1306	Nugent, Brian
1307	Nuida, Koji
1308	Nu'Man, Anisah
1309	Nyandwi, S.
1310	O'Bryant, Kevin
1311	O'Dorney, Evan
1312	Offner, David
1313	Ohno, Yasuo
1314	Ohtsuka, Hideyuki
1315	Ohyama, Hiroshi
1316	Ojah, Kanan Kumari
1317	O'Kuhn, Cooper
1318	Olafson, Hailey
1319	Oliveira e Silva, Tom&aacute;s
1320	Oller-Marc&eacute;n, Antonio M.
1321	Olson, Jeffrey S.
1322	Omar, Mohamed
1323	&Ouml;m&uuml;r, Ne&#x15F;e
1324	O'Neill, Christopher
1325	Ong, Darren C.
1326	Ono, Ken
1327	Orosz, Brooke
1328	Osburn, Robert
1329	O'Shea, Edwin
1330	O'Sullivan, Cathal
1331	O'Sullivan, Cormac
1332	Otmani, Yassine
1333	Ottaway, Paul
1334	Ouellet, Vincent
1335	Ovsienko, Valentin
1336	Owens, C. S.
1337	Oyono, Roger
1338	Ozen, Mustafa
1339	Pach, P&eacute;ter P&aacute;l
1340	Paix&#227;o, Jo&#227;o
1341	Pakianathan, Jonathan
1342	Pakovich, F.
1343	Palka, Ryszard
1344	Palmer, Joseph
1345	Palsson, Eyvindur Ari
1346	Pan, Hao
1347	Pan, Minghao
1348	Pan, Yanbin
1349	Panario, Daniel
1350	Panda, Gopal Krishna
1351	Pandey, Mayank
1352	Pandey, Mohan
1353	Pandey, Prem Prakash
1354	Pandey, Ram Krishna
1355	Panholzer, Alois
1356	Parenti, Salvatore
1357	Paris, Richard B.
1358	Park, Andrew
1359	Park, Poo-Sung
1360	Park, Poo-Sung
1361	Parreau, Aline
1362	Parrish, Joseph
1363	Parshall, Hans
1364	Passant, Jonathan
1365	Patel, Bijan Kumar
1366	Paterson, Mike
1367	Patkowski, Alexander E.
1368	Patra, Asim
1369	Patra, Kamal Lochan
1370	Patra, Sourav Kanti
1371	Patrick, Matthew
1372	Patry, Miriam
1373	Pattanayak, S. K.
1374	Patterson, D.
1375	Paudel, Bishnu
1376	Paul, Krishnendu
1377	Paul, Michael D.
1378	Paul, Prabal
1379	Paul, Shameek
1380	Paule, Peter
1381	Pegado, Sean
1382	Pehlivan, Lerna
1383	Peilloux, Alexis
1384	Pejkovi&cacute;, Tomislav
1385	Pelantov&aacute;, Edita
1386	Peng, Jiangtao
1387	Peng, Junyao
1388	Penland, Andrew
1389	Penman, David
1390	Penniston, David
1391	Pensyl, Thomas W.
1392	Perlmutter, Norman Lewis
1393	Petersen, T. Kyle
1394	Peterson, Carsten
1395	Peth&#337;, Attila
1396	Petrenko, B. V.
1397	Petricevic, Vinko
1398	Petrossian, Armen
1399	Pham, Nhung
1400	Pham, Thang
1401	Philippe, Fabrice
1402	Phillips, David
1403	Phillips, Reed
1404	Phillips, Tristan
1405	Piddle, Melissa
1406	Pigno, Vincent
1407	Pigott, Brian
1408	Pihko, J.
1409	Pikhurko, Oleg
1410	Pilehrood, Khodabakhsh Hessami
1411	Pilehrood, Tatiana Hessami
1412	Pillichshammer, Fridrich
1413	Pineda-Villavicencio, Guillermo
1414	Pinner, Christopher
1415	Pirsic, Gottlieb
1416	Pita-Ruiz, Claudio
1417	Plagne, Alain
1418	Plambeck, Thane E.
1419	Planat, Michel
1420	Plankis, Tomas
1421	Platt, David John
1422	Pleasant, Kendra
1423	Plick, Thomas A.
1424	Pluh&aacute;r, Andr&aacute;s
1425	Poelstra, Andrew
1426	Pohoata, Cosmin
1427	Polasub, Mickey
1428	Pollack, Paul
1429	Pollicott, Mark
1430	Pomales, Luisiany
1431	Pomerance, Carl
1432	Pong, Wai Yan
1433	Pongsriiam, Prapanpong
1434	Ponomarenko, Vadim
1435	Ponton, Lionel
1436	Prakash, Gyan
1437	Prakash, Om
1438	Prasad, Devendra
1439	Prasad, K. V.
1440	Prasad, M.
1441	Pratt, Kyle
1442	Preece, D.A.
1443	Prikhod'ko, Alexander
1444	Pritikin, Dan
1445	Prodinger, Helmut
1446	Propp, James
1447	Puchta, J. -C.
1448	Pudwell, Lara
1449	Punyani, Pooja
1450	Purdum, David
1451	Pyle, E. E.
1452	Qi, Wei-Wei
1453	Qian, Jianguo
1454	Qu, Yongke
1455	Quaintance, Jocelyn
1456	Radoi&#269;i&#263;, Rado&#353;
1457	Radziejewska, Miros&#322;awa
1458	Rafilipojaona, Fanasina
1459	Raghu, Anand
1460	Rajkhowa, Shraddha
1461	Rakotondrajao, Fanja
1462	Ramakrishana, B.
1463	Ramar&eacute;, O.
1464	Ramharter, G.
1465	Ram&iacute;rex Alfons&iacute;n, J.L.
1466	Ram&iacute;rez, Jos&eacute; L.
1467	Rampersad, Narad
1468	Rana, Meenakshi
1469	Randriam, Hugues
1470	Randrianantenaina, Jean Lucien
1471	Rankin, Stuart A.
1472	Rasmussen, Peter Michael Reichstein
1473	Rath, Purusottam
1474	Rathie, Arjun K.
1475	Rattanamoong, Jittinart
1476	R&auml;ty, Eero
1477	Ray, Chiranjit
1478	Ray, Prasanta Kumar
1479	Rayaguru, Sai Gopal
1480	Rechkin, Rebecca
1481	Reddy, A. Satyanarayana
1482	Regev, Alon
1483	Rehberg, Sophie
1484	Rehm, Hunter
1485	Rehmert, Jonathan
1486	Reinholz, Lindsey
1487	Reis, Rog&eacute;rio
1488	Reiter, Harold
1489	Remmel, Jeffrey
1490	Renault, Gabriel
1491	Reutenauer, Christophe
1492	Revuelta, M.P.
1493	Rezig, Boualam
1494	Rho, Yoomi
1495	Rhoades, Robert C
1496	Rhodes, Devon
1497	Riasat, Samin
1498	Ribenboim, Paulo
1499	Ribas, S&aacute;vio
1500	Rib&oacute;, Ares
1501	Ricci, Paolo Emilio
1502	Rice, Alex
1503	Rice, Brian
1504	Richardson, Thomas M.
1505	Richman, David Harry
1506	Richman, David Ross
1507	Richmond, Bruce
1508	Richomme, Gwen&auml;el
1509	Rigo, Michel
1510	Riley, Katherine
1511	Rinaldi, Simone
1512	Rivera, Luis Manuel
1513	Robbins, Neville
1514	Robert, Gerardo Gon&aacute;lez
1515	Robertson, Aaron
1516	Robertson, Leanne
1517	Robinson, Jr., E. Arthur
1518	Robinson, Luc
1519	Robinson, Rhett S.
1520	Roche, James R.
1521	Roche-Newton, Oliver
1522	R&oslash;dseth, &Oslash;ystein J.
1523	Roettger, E. L.
1524	Rosema, S. W.
1525	Ross, John
1526	Rote, G&uuml;nter
1527	Rouse, Jeremy
1528	Rout, S. S.
1529	Rowell, Michael
1530	Rowland, Eric S.
1531	Rowley, Fred
1532	Roy, Bidisha
1533	Rozier, Olivier
1534	Rubinstein, Michael O.
1535	Ruci&nacute;ski, Andrzej
1536	Rudnev, M.
1537	Rudzinski, James
1538	Ru&eacute;, Juanjo
1539	Rushall, Jeff
1540	Ruzsa, Imre
1541	Ryan, Richard F.
1542	Rybnikov, Konstantin
1543	Saba, Nabiha
1544	Sadahiro, Taizo
1545	Sagan, Bruce E.
1546	Sahasrabudhe, Julian
1547	Sahay, Anurag
1548	&#x15E;ahin, Adem
1549	Sahin, Murat
1550	Sahoo, Binod Kumar
1551	Sahs, Marvin L.
1552	Saikia, Anupam
1553	Saikia, Nipen
1554	Saikia, P.K.
1555	Sakai, Yuho
1556	Salerno, Adriana
1557	Salvi, Norma Zagaglia
1558	Samidoost, Payam
1559	Sander, J.W.
1560	Sander, T.
1561	S&aacute;ndor, Csaba
1562	S&aacute;ndor, J&oacute;zsef
1563	Sanna, Carlo
1564	Santiago-Calder&oacute;n, Carlos F.
1565	Santini, Stefano
1566	Santos, Jos&eacute; Pl&iacute;nio O.
1567	Sarkar, Santanu
1568	Sarkar, Subha
1569	S&aacute;rk&ouml;zy, Andra&aacute;s
1570	Sankaranarayanan, Ayyadurai
1571	Sarma, Ritumoni
1572	Sarmah, Bipul Kumar
1573	Sastry, K.R.S.
1574	Sato, Hirotaka
1575	Saunders, J. C.
1576	Savage, Carla D.
1577	Savchev, Svetoslav
1578	Schaal, Daniel
1579	Scharaschkin, Victor
1580	Schlage-Puchta, Jan-Christoph
1581	Schlatter, Mark
1582	Schmid, Wolfgang A.
1583	Schmid, Wolfgang Ch.
1584	Schmidt, Karl Michael
1585	Schmidt, Matthew
1586	Schmidt, Maxie Dion
1587	Schmitt, John R.
1588	Schnabel, Ofir
1589	Schneider, Carsten
1590	Schneider, Robert
1591	Schonbek, Tomas
1592	Schoen, Tomasz
1593	Schramm, Wolfgang
1594	Schulman, Michael
1595	Schumacher, Paul R. F.
1596	Schurman, Iman
1597	Schuyler, Adam
1598	Schwab, Emil Daniel
1599	Schwab, Gabriela
1600	Schweiger, Fritz
1601	Schymura, Matthias
1602	Scott, Reese
1603	Seaberg, Laura
1604	S&eacute;&eacute;bold, Patrice
1605	Seki, Shin-ichiro
1606	Selfridge, John
1607	Selinger, Peter
1608	Seller, Summer
1609	Sellers, James A.
1610	Sengupta, Sayak
1611	Sen Gupta, Sourav
1612	Senger, Steven
1613	Sepanski, Benjamin
1614	Seraj, Samer
1615	Serbenyuk, Symon
1616	Sereni, Jean-S&eacute;bastien
1617	Serra, Oriol
1618	Sertba&#351;, Do&#287;a Can
1619	Setyadi, Alison
1620	Severini, Simone
1621	Shaikh, Md. Moid
1622	Shallit, Jeffrey
1623	Shaman, Paul
1624	Shankar, Ajeet
1625	Shankman, Daniel
1626	Shannon, S. R.
1627	Shao, Lily
1628	Shapiro, Daniel B.
1629	Shapiro, Louis W.
1630	Shapiro, S. David
1631	Shar, Nathaniel
1632	Sharma, Aaditya
1633	Shi, Sanying
1634	Shi, Xiao-Ting
1635	Shim, Peter C.
1636	Shiu, Peter
1637	Shkredov, Ilya D.
1638	Shonhiwa, Temba
1639	Shoukry, K.
1640	Shparlinski, Igor E.
1641	Shattuck, Mark
1642	Sheard, Michael
1643	Shelton, Kennan
1644	Sheikh, Numan
1645	Shekatkar, Snehal M.
1646	Shen, Chun-Yen
1647	Shen, Karen
1648	Shevelev, Vladimir
1649	Siavashi, Sahar
1650	Sicherman, George
1651	Sidorov, Nikita
1652	Sieben, N&aacute;ndor
1653	Siegel, Aaron N.
1654	Siegel, Anne
1655	Siktar, Joshua M.
1656	Sills, Andrew V.
1657	Silva, Elaine
1658	Silva, Jorge Nuno
1659	Simay, Greg
1660	Simbaqueba, Lina Maria
1661	Simonelli, Italo
1662	Simpson, Jamie
1663	Sing, Bernd
1664	Singh, Mritunjay Kumar
1665	Singh, Rajesh P.
1666	Singh, Satyanand
1667	Singhal, Deepesh
1668	Singthongla, P.
1669	Sinha, Nilotpal Kanti
1670	S&icirc;nt&#x00103;m&#x00103;rian, Alina
1671	Sirvent, V&iacute;ctor F.
1672	Sissokho, Papa A.
1673	Sittinger, Brian D.
1674	Sivek, Gary
1675	Sj&ouml;strand, Jonas
1676	Ska&lstrok;ba, Mariusz
1677	Skerritt, Matthew
1678	Skogman, Howard
1679	Skordev, G.
1680	Skula, Ladislav
1681	Skyers, Marina
1682	Slavin, Keith R.
1683	Sledd, Levi
1684	Slezeviciene-Steuding, Rasa
1685	Sloane, N. J. A.
1686	S&#322;ota, Damian
1687	Small, Ben
1688	Smati, A.
1689	Smith, Furman
1690	Smith, Michael
1691	Smith, William W.
1692	Smyth, Chris
1693	Snevily, Hunter
1694	Snider, Lauren
1695	Sofo, Anthony
1696	Solan, Ikhalfani
1697	Sol&eacute;, Patrick
1698	Solymosi, J.
1699	Somer, Lawrence
1700	Somu, Sai Teja
1701	Sondow, Jonathan
1702	Song, Kyunghwan
1703	Sorenson, Jonathan P.
1704	Sorli, Ronald
1705	Souza, Victor
1706	Spearman, Blair K.
1707	Specker, Ernst
1708	Spencer, Craig
1709	Spencer, Craig V.
1710	Sperber, Steven
1711	Spiegel, Christoph
1712	Spiegelhalter, Paul
1713	Spiegelhofer, Lukas
1714	Spier, Thom&aacute;s Jung
1715	Spindler, Mark
1716	Spivey, Michael Z.
1717	Sprugnoli, Renzo
1718	Sprunger, Carsten
1719	Sridharan, Manu
1720	Srilakshmi, K.
1721	Srinivasan, Anitha
1722	Sriram, S.
1723	Srivastava, Anshika
1724	Stahl, Aryn
1725	Stamp, Mark
1726	Stanchescu, Yonutz V.
1727	Stanger, Adrian Dan
1728	St&#259;nic&#259;, Pantelimon
1729	Stankewicz, James
1730	Stanton, Caitlin
1731	Staps, Merlijn
1732	Stack, Jason
1733	Stein, Alan H.
1734	Stein, Martin
1735	Steinberger, John
1736	Steiner, Wolfgang
1737	Steinerberger, Stefan
1738	Stender, Matthew
1739	Steuding, J&ouml;rn
1740	Stevens, Brett
1741	Stewart, Fraser
1742	Stipulanti, Manon
1743	Stocker, Christopher
1744	Stoiciu, Mihai
1745	Stoll, Peter
1746	Stoll, Thomas
1747	Stones, Rebecca J.
1748	Stopple, Jeffrey
1749	Straub, Armin
1750	Strauch, Oto
1751	Strauss, Dona
1752	Strimling, Pontus
1753	Stromquist, Walter
1754	Strzebonski, Adam
1755	Stumpf, Pascal
1756	Styer, Robert
1757	Subramaniam, Dipika
1758	Suda, Sho
1759	Suh, Hong
1760	Sukruan, Lalitphat
1761	Sullivan, Blair D.
1762	Sullivan, Rosemary
1763	Sullivan, Shaun
1764	Sun, Liang
1765	Sun, Xinjie
1766	Sun, Xinyu
1767	Yewen, Sun
1768	Sun, Zhi-Wei
1769	Sundberg, Eric
1770	Surahmat
1771	Sury, B.
1772	Swisher, Holly
1773	Szab&oacute, Csaba
1774	Szab&oacute;, S&aacute;ndor
1775	Szalay, L&aacute;szl&oacute;
1776	Ta, Ha
1777	Tachiya, Yohei
1778	Tada, Masato
1779	Tagami, Makoto
1780	Tahay, Pierre-Adrien
1781	Tajbakhsh, H.
1782	Takalani, Ntendeni A.
1783	Takeda, Wataru
1784	Talbot, John
1785	Tall, Amadou
1786	Tan, Elif
1787	Tan, Eng-Tjioe
1788	Tan, Xin Lu
1789	Tait, Michael
1790	Tanabe, Naomi
1791	Tang, Chi-Wu
1792	Tang, Dazhao
1793	Tang, Hengcai
1794	Tang, Min
1795	Tang, Tai-Man
1796	Tanimoto, Shinji
1797	Tanny, Yuval
1798	Tarnu, Daniel
1799	Tauraso, Roberto
1800	Taylor, Clifford
1801	Tchammou, Euloge
1802	Tebon, Suzannah
1803	Tedford, Steven J.
1804	Tefera, Akalu
1805	Temple, Kathryn E.
1806	Teng, Shang-Hua
1807	Tennenhouse, Craig
1808	Tenner, Bridget Eileen
1809	te Riele, Herman
1810	Te&#351;eleanu, George
1811	Thangadurai, R.
1812	Thiel, Johann
1813	Thomas, Neha Elizabeth
1814	Thompson, Katherine
1815	Thompson, Kimberly
1816	Thompson, Lola
1817	Thorne, Frank
1818	Thornton, DJ
1819	Thuswaldner, J&ouml;rg
1820	Tiachachat, Meriem
1821	Tian, Peter
1822	Tichenor, Todd
1823	Tiefenbruck, Mark
1824	Tijdeman, Robert
1825	Timmons, Craig
1826	Togb&eacute;, Alain
1827	Toh, Pee Choon
1828	Tokaz, Jacent
1829	Tollisen, Gregory
1830	Tomasko, Jessica A.
1831	Tomkins, Hayley
1832	Tomovski, Zivorad
1833	Tongsomporn, Janyarak
1834	Tonien, Joseph
1835	Top, Jaap
1836	Tor, Kimsy
1837	Torf, Jordan N.
1838	Tossavainen, Timo
1839	T&oacute;th, L&aacute;szl&oacute;
1840	Travis, Jennifer
1841	Trenton, M. A.
1842	Trevi&ntilde;o, Enrique
1843	Triantafillou, Nicholas George
1844	Trifonov, Ognian
1845	Tringali, Salvatore
1846	Trinh, Minh-Tam
1847	Tripathi, Amitabha
1848	Tripathy, Bibhu Prasad
1849	Trudgian, Tim
1850	Trujillo, Timothy
1851	Trukszyn, Zdzislaw
1852	Tsai, Daniel
1853	Tsegaye, Bineyam
1854	Tseng, Dennis
1855	Tsumura, Yu
1856	Tucker, Amanda
1857	Tung, Katherine
1858	Turnage-Butterbaugh, Caroline
1859	Ulas, Maciej
1860	Uncini, Francesca
1861	Urbanski, Michael T.
1862	Urick, Jim
1863	Urroz, Jorge Jim&eacute;nez
1864	Ushiroya, Noboru
1865	Valli&egrave;res, Daniel
1866	Van Alten, Clint
1867	van der Kamp, Peter H.
1868	Vandehey, Joseph
1869	Vanegas, Elkin Quintero
1870	Vanlalngaia, Ramdinmawia
1871	Van Peski, Roger
1872	Vary, Robert G.
1873	Vassilev, Tzvetalin S.
1874	Veeranna, Y.
1875	Veeranayaka, T. N.
1876	Velich, Jordan
1877	Velk&aacute;, Tereza
1878	Vella, David C.
1879	Verbitsky, Oleg
1880	Verger-Gaugry, Jean-Louis
1881	Vergne, Mich&egrave;le
1882	Verreault, William
1883	Verri, M. Cecilia
1884	Vieira, Renata Passos Machado
1885	Vijay, Sujith
1886	Villacorta, Jorge Luis Cimadevilla
1887	Vinagre, Sandra
1888	Vincent, Andrew
1889	Vinh, Le Anh
1890	Vipismakul, Wasin
1891	Vishwakarma, Chandan Kumar
1892	Viswanadham, G. K.
1893	Vo, Anh
1894	Volkert, Klaus
1895	Voloch, Felipe Jos&eacute;
1896	von Heymann, Frederik
1897	Voss, K.
1898	Vu, V. H.
1899	Vu, Yen Nhi Truong
1900	Vukusic, Ingrid
1901	Vyalyi, Michael
1902	Vyncke, Pieter
1903	Wagner, Joshua
1904	Wagon, Stan
1905	Wagstaff, S. S., Jr.
1906	Wahlenmayer, Catherine
1907	Wakefield, Thomas P.
1908	Wakeham, David
1909	Wakhare, Tanay
1910	Walsh, Alexandra
1911	Walsh, P. G.
1912	Walsh, Steven
1913	Walters, Nathan
1914	Wan, James
1915	Wananiyakul, Saeree
1916	Wang, Chen-Ying
1917	Wang, Chunlin
1918	Wang, Dan
1919	Wang, Guoqing
1920	Wang, Haiqing
1921	Wang, Hua
1922	Wang, Jun
1923	Wang, Linlin
1924	Wang, Liuquan
1925	Wang, Qiang
1926	Wang, Qinghong
1927	Wang, Tianming
1928	Wang, Wei
1929	Wang, Wenjie
1930	Wang, Yan
1931	Wang, Xiaoxia
1932	Wang, Xiaoyuan
1933	Wang, Yichen
1934	Wang, Zhaonan
1935	Wanner, Mathias
1936	Ward, Mark Daniel
1937	Warnberg, Nathan
1938	Warnick, Merrill
1939	Warren, Audie
1940	W&auml;stlund, Johan
1941	Watling, Neil
1942	Watson, Lori D.
1943	Waxweiler, Laurent
1944	Weba, Michael
1945	Webster, Jonathan
1946	Wei, Chuanan
1947	Wei, Linli
1948	Wei, Wandi
1949	Wei, Yi
1950	Weiner, Michael D.
1951	Weingartner, Andreas
1952	Weinstein, Madeleine
1953	Weitzer, Mario
1954	Wells, Matthew
1955	Weselcouch, Michael
1956	White, Daniel
1957	White, Susan Calcote
1958	Wiechert, Veit
1959	Wildstrom, D. Jacob
1960	Wilf, Herbert S.
1961	Willette, Michael
1962	Williams, H. C.
1963	Williams, Kenneth S.
1964	Wilson, Bryan
1965	Winkler, Peter
1966	Winterhof, Arne
1967	Withrow, Camron
1968	Witno, Amin
1969	Witu&#322;a, Roman
1970	Klaudiusz W&oacute;jcik, Klaudiusz
1971	Wolfe, David
1972	Wolird, Christian
1973	Woltman, George
1974	Wong, Erick B.
1975	Wong, Tian An
1976	Wong, Tony W. H.
1977	Wood, David R.
1978	Wood, Philip Matchett
1979	Woodford, Roger
1980	Woodson, Leon C.
1981	Wright, Thomas
1982	Wu, Chai Wah
1983	Xia, Xingwu
1984	Xu, Ping
1985	Xue, Hui
1986	Yamada, Tomohiro
1987	Yamagami, Atsushi
1988	Yamaguchi, Naoya
1989	Yamaguchi, Yuka
1990	Yamamoto, Shuji
1991	Catherine Yan
1992	Yan, Lu
1993	Yang, Dan-Mei
1994	Yang, Mingjia
1995	Yang, Qianqian
1996	Yang, Qiduan
1997	Yang, Quan-Hui
1998	Yang, Shichun
1999	Yankov, Christian L.
2000	Yao, Jialing
2001	Yassawi, Reem
2002	Yayenie, Omer
2003	Ye, Dongxi
2004	Ye, Lynnelle
2005	Yee, Ae Ja
2006	Yeroshkin, Dmytro
2007	Yildirim, C. Y.
2008	Yip, Chi Hoi
2009	Yiu, Paul
2010	Yokura, Shoji
2011	Yoshino, Kiyoto
2012	Young, Michael
2013	Young, Paul Thomas
2014	Yu, Gang
2015	Yu, Jing-Jun
2016	Yu, Wen
2017	Yuan, Pingzhi
2018	Yuan, Xueying
2019	Yue, Heng
2020	Zaleski, Anthony
2021	Zamboni, Luca Q.
2022	Zargar, Arman Shamsi
2023	Zbacnik, Nathaniel
2024	Zeilberger, Doron
2025	Zeleke, Aklilu
2026	Zeleke, Melkamu
2027	Zelinsky, Joshua
2028	Zemor, Gilles
2029	Zemyan, Stephen M.
2030	Zeng, Jiang
2031	Zeng, Tony
2032	Zeng, Xiangneng
2033	Zhan, Tong
2034	Zhang, Min
2035	Zhang, Philip B.
2036	Zhang, Shaohua
2037	Zhang, Wentao
2038	Zhang, Yanbo
2039	Zhang, Yong
2040	Zhang, Zhizheng
2041	Zhang, Zhongfeng
2042	Zhao, Alina F. Y.
2043	Zhao, Feng-Zhen
2044	Zhao, Jianqiang
2045	Zhao, Kanglun
2046	Zhao, Kevin
2047	Zhao, Liangyi
2048	Zheng, Jinze
2049	Zheng, Qi-Yang
2050	Zhong, Qinghai
2051	Zhou, Qizhi
2052	Zhao, Rosie Y.
2053	Zhou, Weiyi
2054	Zhou, Zhi-Jun
2055	Zhu, Long
2056	Zhu, Yuyang
2057	Zhuang, Yan
2058	Ziegler, Volker
2059	Zielinski, Ryan
2060	Zinnel, Laura
2061	Zou, Aiyue
